version: '3.1'

services:
    # Change this if your want use your own application.
    # It's very important expose your application in port 5442
    # and use the http protocol.
    app:
        image: openvidu/openvidu-call:2.12.0
        restart: on-failure
        ports:
            - "5442:80"
        environment: 
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
